[package]
name = "tkr-agent"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "tkr_agent"
crate-type = ["rlib"]

[dependencies]
tkr-api = { path = "../tkr-api" }
tkr-filter = { path = "../tkr-filter" }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
mockito = { workspace = true }
