[package]
name = "jkr-session-recorder"
publish = false
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
license = "Apache-2.0"

[lib]
name = "jkr_session_recorder"
crate-type = ["rlib"]

[dependencies]
jkr-api = { path = "../jkr-api" }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }

[features]
test-host = ["jkr-api/test-host"]
