[package]
name = "tkr-session-recorder"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
license = "Apache-2.0"

[lib]
name = "tkr_session_recorder"
crate-type = ["rlib"]

[dependencies]
tkr-api = { path = "../tkr-api" }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }

[features]
test-host = ["tkr-api/test-host"]
