[package]
name = "tkr-server"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
license = "Apache-2.0"

[[bin]]
name = "tkr-server"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
futures-util = { version = "0.3", default-features = false, features = ["sink"] }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { version = "0.21", default-features = false }
tkr-mesh = { path = "../tkr-mesh" }
rand = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
k256 = { version = "0.13", features = ["ecdsa", "ecdh", "sha256"] }
tokio = { workspace = true, features = ["macros"] }
ureq = { workspace = true }
